---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang

inputs:
- name: stemcell
- name: os-conf-release
- name: bbl-state

params:
  BOSH_STEMCELL: ~
  BOSH_DEPLOYMENT: ~

run:
  path: os-conf-release/ci/tasks/run-acceptance-tests.sh
